// Generated by tests/generate_corpus.py. Do not edit by hand.
function build(seed) {
  var value0 = seed; var value1 = value0 + 1; var value2 = value1 + 2; var value3 = value2 + 3; var value4 = value3 + 4; var value5 = value4 + 5; var value6 = value5 + 6; var value7 = value6 + 7; var value8 = value7 + 8;
  return function (step) { value0 += step; return value0 + value1 + value2 + value3 + value4 + value5 + value6 + value7 + value8; };
}
var first = build(3), second = build(7);
print("closure-capture-8", first(1), first(2), second(4));
