// Generated by tests/generate_corpus.py. Do not edit by hand.
function build(seed) {
  var value0 = seed; var value1 = value0 + 1; var value2 = value1 + 2; var value3 = value2 + 3; var value4 = value3 + 4; var value5 = value4 + 5; var value6 = value5 + 6; var value7 = value6 + 7; var value8 = value7 + 8; var value9 = value8 + 9; var value10 = value9 + 10; var value11 = value10 + 11; var value12 = value11 + 12; var value13 = value12 + 13; var value14 = value13 + 14; var value15 = value14 + 15; var value16 = value15 + 16; var value17 = value16 + 17; var value18 = value17 + 18; var value19 = value18 + 19; var value20 = value19 + 20; var value21 = value20 + 21; var value22 = value21 + 22; var value23 = value22 + 23; var value24 = value23 + 24; var value25 = value24 + 25; var value26 = value25 + 26; var value27 = value26 + 27; var value28 = value27 + 28; var value29 = value28 + 29; var value30 = value29 + 30; var value31 = value30 + 31; var value32 = value31 + 32;
  return function (step) { value0 += step; return value0 + value4 + value8 + value12 + value16 + value20 + value24 + value28 + value32; };
}
var first = build(3), second = build(7);
print("closure-capture-32", first(1), first(2), second(4));
