// Generated by tests/generate_corpus.py. Do not edit by hand.
function choose(value) {
              switch (value) {
                case 0: return 0;
case 1: return 13;
case 2: return 26;
case 3: return 39;
case 4: return 52;
case 5: return 65;
case 6: return 78;
case 7: return 91;
case 8: return 104;
case 9: return 117;
case 10: return 130;
case 11: return 143;
case 12: return 156;
case 13: return 169;
case 14: return 182;
case 15: return 195;
                default: return -1;
              }
            }
            var checksum = 0;
            for (var i = -1; i <= 16; i++) checksum = (checksum * 33 + choose(i)) | 0;
            print("large-switch-16", checksum, choose(8), choose(17));
