// Generated by tests/generate_corpus.py. Do not edit by hand.
var object = {
            p0: 0,
p1: 3,
p2: 6,
p3: 9,
p4: 12,
p5: 15,
p6: 18,
p7: 21,
p8: 24,
p9: 27,
p10: 30,
p11: 33,
p12: 36,
p13: 39,
p14: 42,
p15: 45,
p16: 48,
p17: 51,
p18: 54,
p19: 57,
p20: 60,
p21: 63,
p22: 66,
p23: 69,
p24: 72,
p25: 75,
p26: 78,
p27: 81,
p28: 84,
p29: 87,
p30: 90,
p31: 93
            };
            var checksum = 0, keys = Object.keys(object);
            for (var i = 0; i < keys.length; i++) checksum = (checksum * 31 + object[keys[i]]) | 0;
            print("many-properties-32", keys.length, checksum, object.p31);
