// Generated by tests/generate_corpus.py. Do not edit by hand.
var a=12345678901234567890n,b=987654321n; var c=(a*b)+(a>>7n)-(b<<11n);
var values=[1n,2n,3n,4n,5n],product=1n;for(var value of values)product*=value;
print("bigint",String(c),String(product),a>b,String(BigInt("9007199254740993")+1n));
