// Generated by tests/generate_corpus.py. Do not edit by hand.
var date=new Date(1609459200123), checksum=0;
for(var i=1;i<=100;i++)checksum+=Math.floor(Math.sin(i)*1000)+Math.ceil(Math.cos(i)*1000)+Math.round(Math.log(i)*100);
print("date-math",date.getTime(),date.getUTCFullYear(),date.getUTCMonth(),date.getUTCDate(),checksum,Math.max(3,9,-1),Math.min(3,9,-1));
