// Generated by tests/generate_corpus.py. Do not edit by hand.
var value={name:"mercury",values:[1,true,null,"x"],nested:{b:2,a:1}};
var encoded=JSON.stringify(value),decoded=JSON.parse(encoded),revived=JSON.parse('{"x":2,"y":3}',function(key,value){return typeof value==="number"?value*4:value;});
print("json",encoded,decoded.values.join("|"),decoded.nested.a+decoded.nested.b,revived.x+revived.y);
