// Generated by tests/generate_corpus.py. Do not edit by hand.
var regexp=/(a+)(b?)/gi, input="aaB aaaa ab", matches=[], match;
while((match=regexp.exec(input))!==null)matches.push(match.index+":"+match[0]+":"+match[1]+":"+match[2]);
var replaced=input.replace(/a+/g,function(value){return "["+value.length+"]";});
print("regexp",matches.join("|"),replaced,/^aaB/i.test(input));
