// Generated by tests/generate_corpus.py. Do not edit by hand.
var text="A😀B\ud800C\udfff"; var units=[]; for(var i=0;i<text.length;i++)units.push(text.charCodeAt(i).toString(16));
var repeated="ab".repeat(5), pieces="alpha,beta,,delta".split(",");
print("strings",text.length,units.join("-"),repeated,pieces.join("|"),"  trim  ".trim(),"banana".indexOf("na",3));
