// Generated by tests/generate_corpus.py. Do not edit by hand.
var buffer=new ArrayBuffer(32),view=new DataView(buffer),bytes=new Uint8Array(buffer),words=new Int32Array(buffer);
for(var i=0;i<bytes.length;i++)bytes[i]=(i*17+3)&255;
view.setInt32(4,-12345678,true);view.setUint16(12,65530,false);words[5]=0x12345678;
var checksum=0;for(var i=0;i<bytes.length;i++)checksum=(checksum*33+bytes[i])|0;
print("typed",view.getInt32(4,true),view.getUint16(12,false),words[5],checksum);
