#!/usr/bin/env python3
"""Generate deterministic standalone JavaScript roundtrip corpus files."""

from pathlib import Path
from textwrap import dedent
import sys


ROOT = Path(__file__).with_name("corpus")
HEADER = "// Generated by tests/generate_corpus.py. Do not edit by hand.\n"


CASES = {
    "arithmetic/numeric_edges.js": r"""
        var values = [0, -0, 1, -1, 3.5, -7.25, 2147483647, -2147483648, Infinity, -Infinity, NaN];
        var checksum = 0;
        for (var i = 0; i < values.length; i++) {
          var value = values[i];
          checksum += (value | 0) ^ (value >>> 0);
        }
        print("numeric", checksum, 1 / values[1], Number.isNaN(values[10]), Math.imul(123456, 789));
    """,
    "arithmetic/fibonacci.js": r"""
        function fib(n) {
          var a = 0, b = 1;
          for (var i = 0; i < n; i++) { var next = a + b; a = b; b = next; }
          return a;
        }
        var checksum = 0;
        for (var i = 0; i <= 30; i++) checksum = (checksum + fib(i)) | 0;
        print("fibonacci", fib(10), fib(20), fib(30), checksum);
    """,
    "arithmetic/gcd_lcg.js": r"""
        function gcd(a, b) { while (b) { var next = a % b; a = b; b = next; } return a; }
        var state = 0x12345678;
        var checksum = 0;
        for (var i = 1; i <= 2000; i++) {
          state = (Math.imul(state, 1664525) + 1013904223) | 0;
          checksum = (checksum + gcd((state >>> 0) % 100000 + 1, i * 37)) | 0;
        }
        print("gcd-lcg", state, checksum);
    """,
    "algorithms/sieve.js": r"""
        function countPrimes(limit) {
          var composite = new Uint8Array(limit + 1);
          var count = 0, checksum = 0;
          for (var value = 2; value <= limit; value++) {
            if (!composite[value]) {
              count++; checksum = (checksum + value) | 0;
              if (value * value <= limit) {
                for (var multiple = value * value; multiple <= limit; multiple += value) composite[multiple] = 1;
              }
            }
          }
          return [count, checksum];
        }
        var result = countPrimes(10000);
        print("sieve", result[0], result[1]);
    """,
    "algorithms/sorting.js": r"""
        function randomValues(length) {
          var state = 1, values = [];
          for (var i = 0; i < length; i++) { state = (Math.imul(state, 1103515245) + 12345) | 0; values.push(state); }
          return values;
        }
        function quicksort(values, left, right) {
          if (left >= right) return;
          var pivot = values[(left + right) >> 1], i = left, j = right;
          while (i <= j) {
            while (values[i] < pivot) i++;
            while (values[j] > pivot) j--;
            if (i <= j) { var value = values[i]; values[i++] = values[j]; values[j--] = value; }
          }
          if (left < j) quicksort(values, left, j);
          if (i < right) quicksort(values, i, right);
        }
        var values = randomValues(1000);
        quicksort(values, 0, values.length - 1);
        var checksum = 0;
        for (var i = 0; i < values.length; i += 17) checksum = (checksum + values[i]) | 0;
        print("sorting", values[0], values[values.length - 1], checksum);
    """,
    "algorithms/matrix.js": r"""
        function matrix(size, seed) {
          var result = new Array(size);
          for (var row = 0; row < size; row++) {
            result[row] = new Array(size);
            for (var column = 0; column < size; column++) result[row][column] = (row * 17 + column * 13 + seed) % 19;
          }
          return result;
        }
        function multiply(left, right) {
          var size = left.length, output = matrix(size, 0);
          for (var row = 0; row < size; row++) for (var column = 0; column < size; column++) {
            var value = 0;
            for (var index = 0; index < size; index++) value += left[row][index] * right[index][column];
            output[row][column] = value;
          }
          return output;
        }
        var output = multiply(matrix(18, 3), matrix(18, 7));
        var checksum = 0;
        for (var i = 0; i < output.length; i++) checksum += output[i][i] + output[i][17 - i];
        print("matrix", checksum, output[3][7]);
    """,
    "algorithms/binary_trees.js": r"""
        function Node(left, right, value) { this.left = left; this.right = right; this.value = value; }
        function build(depth, value) {
          if (depth === 0) return new Node(null, null, value);
          return new Node(build(depth - 1, value * 2 - 1), build(depth - 1, value * 2), value);
        }
        function check(node) { return node.left === null ? node.value : node.value + check(node.left) - check(node.right); }
        var checksum = 0;
        for (var i = 0; i < 20; i++) checksum += check(build(8, i + 1));
        print("binary-trees", checksum, check(build(10, 1)));
    """,
    "algorithms/graph.js": r"""
        var size = 120;
        var graph = new Array(size);
        for (var i = 0; i < size; i++) graph[i] = [(i * 7 + 3) % size, (i * 11 + 5) % size, (i + 1) % size];
        var distance = new Int32Array(size);
        for (var i = 0; i < size; i++) distance[i] = -1;
        var queue = [0]; distance[0] = 0;
        for (var head = 0; head < queue.length; head++) {
          var node = queue[head];
          for (var edge = 0; edge < graph[node].length; edge++) {
            var next = graph[node][edge];
            if (distance[next] === -1) { distance[next] = distance[node] + 1; queue.push(next); }
          }
        }
        var checksum = 0;
        for (var i = 0; i < size; i++) checksum = (checksum * 31 + distance[i]) | 0;
        print("graph", queue.length, checksum);
    """,
    "algorithms/mandelbrot.js": r"""
        var checksum = 0, width = 80, height = 60;
        for (var py = 0; py < height; py++) for (var px = 0; px < width; px++) {
          var x0 = px / width * 3.5 - 2.5, y0 = py / height * 2 - 1;
          var x = 0, y = 0, iteration = 0;
          while (x * x + y * y <= 4 && iteration < 50) {
            var nextX = x * x - y * y + x0;
            y = 2 * x * y + y0; x = nextX; iteration++;
          }
          checksum = (checksum + Math.imul(iteration, px + py + 1)) | 0;
        }
        print("mandelbrot", checksum);
    """,
    "algorithms/spectral_norm.js": r"""
        function A(i, j) { var ij = i + j; return 1 / ((ij * (ij + 1) / 2) + i + 1); }
        function multiplyAv(input, output) {
          for (var i = 0; i < input.length; i++) { var sum = 0; for (var j = 0; j < input.length; j++) sum += A(i, j) * input[j]; output[i] = sum; }
        }
        function multiplyAtv(input, output) {
          for (var i = 0; i < input.length; i++) { var sum = 0; for (var j = 0; j < input.length; j++) sum += A(j, i) * input[j]; output[i] = sum; }
        }
        var n = 70, u = new Float64Array(n), v = new Float64Array(n), temp = new Float64Array(n);
        for (var i = 0; i < n; i++) u[i] = 1;
        for (var iteration = 0; iteration < 8; iteration++) { multiplyAv(u, temp); multiplyAtv(temp, v); multiplyAv(v, temp); multiplyAtv(temp, u); }
        var vbv = 0, vv = 0;
        for (var i = 0; i < n; i++) { vbv += u[i] * v[i]; vv += v[i] * v[i]; }
        print("spectral-norm", Math.sqrt(vbv / vv).toFixed(9));
    """,
    "algorithms/nbody.js": r"""
        var bodies = [
          {x:0,y:0,z:0,vx:0,vy:0,vz:0,m:1},
          {x:1,y:0,z:0,vx:0,vy:0.8,vz:0,m:0.001},
          {x:-1.5,y:0.2,z:0,vx:-0.1,vy:-0.6,vz:0,m:0.0007},
          {x:0.3,y:2,z:0.1,vx:-0.5,vy:0.1,vz:0,m:0.0002}
        ];
        function advance(dt) {
          for (var i = 0; i < bodies.length; i++) for (var j = i + 1; j < bodies.length; j++) {
            var a = bodies[i], b = bodies[j], dx = a.x-b.x, dy=a.y-b.y, dz=a.z-b.z;
            var distance = Math.sqrt(dx*dx+dy*dy+dz*dz), scale = dt/(distance*distance*distance);
            a.vx -= dx*b.m*scale; a.vy -= dy*b.m*scale; a.vz -= dz*b.m*scale;
            b.vx += dx*a.m*scale; b.vy += dy*a.m*scale; b.vz += dz*a.m*scale;
          }
          for (var i = 0; i < bodies.length; i++) { var b=bodies[i]; b.x+=dt*b.vx; b.y+=dt*b.vy; b.z+=dt*b.vz; }
        }
        function energy() {
          var result=0;
          for(var i=0;i<bodies.length;i++){var a=bodies[i];result+=a.m*(a.vx*a.vx+a.vy*a.vy+a.vz*a.vz)/2;for(var j=i+1;j<bodies.length;j++){var b=bodies[j],dx=a.x-b.x,dy=a.y-b.y,dz=a.z-b.z;result-=a.m*b.m/Math.sqrt(dx*dx+dy*dy+dz*dz);}}
          return result;
        }
        for(var i=0;i<2000;i++) advance(0.001);
        print("nbody", energy().toFixed(12), bodies[1].x.toFixed(9));
    """,
    "collections/maps_sets.js": r"""
        var map = new Map(), set = new Set();
        for (var i = 0; i < 200; i++) { var key = "k" + (i % 73); map.set(key, (map.get(key) || 0) + i); set.add(i % 41); }
        var checksum = 0;
        map.forEach(function (value, key) { checksum = (checksum + value * key.length) | 0; });
        var iterated = 0;
        for (var value of set) iterated = (iterated * 33 + value) | 0;
        print("maps-sets", map.size, set.size, checksum, iterated, map.has("k17"));
    """,
    "collections/weak_collections.js": r"""
        var weakMap = new WeakMap(), weakSet = new WeakSet(), objects = [];
        for (var i = 0; i < 50; i++) { var object = {index:i}; objects.push(object); weakMap.set(object, i*i); if (i%2===0) weakSet.add(object); }
        var checksum = 0, membership = 0;
        for (var i = 0; i < objects.length; i++) { checksum += weakMap.get(objects[i]); membership += weakSet.has(objects[i]) ? 1 : 0; }
        print("weak-collections", checksum, membership);
    """,
    "language/closures.js": r"""
        function counter(seed) {
          var value = seed;
          return { next: function(step){ value += step; return value; }, read: function(){ return value; } };
        }
        var counters = [];
        for (let i = 0; i < 12; i++) counters.push(function(){ return i * i; });
        var first = counter(10), second = counter(-3), checksum = 0;
        for (var i = 0; i < counters.length; i++) checksum += counters[i]();
        print("closures", first.next(2), first.next(5), second.next(7), first.read(), second.read(), checksum);
    """,
    "language/objects.js": r"""
        var events = [], key = "dynamic", symbol = Symbol("s");
        var source = {a:1, get b(){events.push("get-b");return 2;}}; source[symbol] = 3;
        var parent = {inherited:4};
        var object = {__proto__:parent, before:0, ...source, [key]:5, method(x){return this.inherited+x;}, get value(){return this._v||6;}, set value(v){events.push("set");this._v=v;}};
        object.value=7;
        var descriptor=Object.getOwnPropertyDescriptor(object,"value");
        print("objects",object.a,object.b,object[symbol],object.dynamic,object.method(8),object.value,descriptor.enumerable,parent.isPrototypeOf(object),events.join(","));
    """,
    "language/prototypes.js": r"""
        function Base(value){this.value=value;} Base.prototype.read=function(){return this.value;};
        function Child(value){Base.call(this,value*2);} Child.prototype=Object.create(Base.prototype); Child.prototype.constructor=Child;
        Child.prototype.bump=function(){this.value++;return this.value;};
        var child=new Child(9);
        print("prototypes",child.read(),child.bump(),child instanceof Child,child instanceof Base,Object.getPrototypeOf(child)===Child.prototype);
    """,
    "language/classes.js": r"""
        class Base { constructor(value){this.value=value;} get doubled(){return this.value*2;} method(step){return this.value+step;} static label(){return "base";} }
        class Derived extends Base { constructor(value){super(value+1);} method(step){return super.method(step)*2;} set doubled(value){this.value=value/2;} static label(){return super.label()+"-derived";} }
        var item=new Derived(10), first=item.method(3); item.doubled=50;
        print("classes",first,item.value,Derived.label(),item instanceof Derived,item instanceof Base);
    """,
    "language/arrays.js": r"""
        var source=[1,,3], values=[0,...source,4,..."xy"], removed=values.splice(2,2,8,9,10);
        values.unshift(-1); values.push(11); var mapped=values.map(function(v,i){return v===undefined?i:v*i;});
        var checksum=0; for(var i=0;i<mapped.length;i++) checksum=(checksum+(mapped[i]||0))|0;
        print("arrays",values.length,1 in source,removed.join("|"),values.join("|"),checksum);
    """,
    "language/destructuring.js": r"""
        function collect(first=1,{x,y=3,...rest},[head,,...tail]){return [first,x,y,rest.z,head,tail.join(":"),arguments.length];}
        var input={x:2,z:4}, array=[5,6,7,8]; var result=collect(undefined,input,array);
        var a,b,remaining; [a,b,...remaining]=[9,10,11,12];
        print("destructuring",result.join("|"),a,b,remaining.join(":"));
    """,
    "language/iterators.js": r"""
        var closed=0;
        var iterable={}; iterable[Symbol.iterator]=function(){var i=0;return{next:function(){return i<8?{value:i++,done:false}:{done:true};},return:function(){closed++;return{done:true};}};};
        var checksum=0; for(var value of iterable){if(value===5)break;checksum=checksum*10+value;}
        var spread=[...iterable];
        print("iterators",checksum,closed,spread.join(","));
    """,
    "language/generators.js": r"""
        function* sequence(limit){try{for(var i=0;i<limit;i++)yield i*i;}finally{yield "closed";}}
        var iterator=sequence(5), output=[]; output.push(iterator.next().value); output.push(iterator.next().value); output.push(iterator.return(9).value); output.push(iterator.next().value); output.push(iterator.next().done);
        function* delegated(){yield 1;yield* [2,3];return 4;} var second=delegated(), checksum=[]; var step; while(!(step=second.next()).done)checksum.push(step.value); checksum.push(step.value);
        print("generators",output.join("|"),checksum.join("|"));
    """,
    "language/async.js": r"""
        async function calculate(value){var first=await Promise.resolve(value+1);try{await Promise.reject(3);}catch(error){first+=error;}return first*2;}
        Promise.all([calculate(4),calculate(9)]).then(function(values){print("async",values.join(","));});
    """,
    "language/exceptions.js": r"""
        var log=[];
        function work(value){try{log.push("try"+value);if(value%2)throw value;return value*2;}catch(error){log.push("catch"+error);return error+10;}finally{log.push("finally"+value);}}
        var checksum=0; for(var i=0;i<6;i++)checksum+=work(i);
        try{try{throw "inner";}finally{log.push("inner-finally");}}catch(error){log.push(error);}
        print("exceptions",checksum,log.join(","));
    """,
    "language/coercions.js": r"""
        var object={valueOf:function(){return 7;},toString:function(){return "object";}};
        var values=[null,undefined,false,true,0,-0,1,"", "12", object]; var checksum="";
        for(var i=0;i<values.length;i++)checksum+=typeof values[i]+":"+Boolean(values[i])+"|";
        print("coercions",+"12",object+3,String(object),null==undefined,null===undefined,0==false,checksum.length);
    """,
    "language/scoping.js": r"""
        var output=[];
        for(let i=0;i<5;i++){let square=i*i;output.push(function(){return i+":"+square;});}
        function outer(value){var shared=value;function left(){return ++shared;}function right(){shared*=2;return shared;}return[left,right];}
        var pair=outer(3);
        print("scoping",output.map(function(fn){return fn();}).join(","),pair[0](),pair[1](),pair[0]());
    """,
    "language/arguments.js": r"""
        function inspect(a,b){a=10;arguments[1]=20;return[a,b,arguments[0],arguments[1],arguments.length].join(":");}
        function rest(first,...values){return first+":"+values.join(",")+":"+arguments.length;}
        var arrow=()=>arguments.length;
        print("arguments",inspect(1,2,3),rest(4,5,6,7),arrow());
    """,
    "language/proxy_reflect.js": r"""
        var log=[],target={value:2};
        var proxy=new Proxy(target,{get:function(object,key,receiver){log.push("g"+String(key));return Reflect.get(object,key,receiver);},set:function(object,key,value,receiver){log.push("s"+String(key));return Reflect.set(object,key,value,receiver);},ownKeys:function(object){log.push("keys");return Reflect.ownKeys(object);}});
        proxy.value+=5;proxy.extra=9;var keys=Object.keys(proxy);
        print("proxy",proxy.value,proxy.extra,keys.join(","),log.join("|"));
    """,
    "language/symbols.js": r"""
        var first=Symbol("x"), second=Symbol.for("shared"), object={}; object[first]=3; object[second]=4; object.visible=5;
        var symbols=Object.getOwnPropertySymbols(object), checksum=0; for(var i=0;i<symbols.length;i++)checksum+=object[symbols[i]];
        print("symbols",symbols.length,checksum,Symbol.keyFor(second),String(first),Reflect.ownKeys(object).length);
    """,
    "runtime/strings_unicode.js": r"""
        var text="A😀B\ud800C\udfff"; var units=[]; for(var i=0;i<text.length;i++)units.push(text.charCodeAt(i).toString(16));
        var repeated="ab".repeat(5), pieces="alpha,beta,,delta".split(",");
        print("strings",text.length,units.join("-"),repeated,pieces.join("|"),"  trim  ".trim(),"banana".indexOf("na",3));
    """,
    "runtime/regexp.js": r"""
        var regexp=/(a+)(b?)/gi, input="aaB aaaa ab", matches=[], match;
        while((match=regexp.exec(input))!==null)matches.push(match.index+":"+match[0]+":"+match[1]+":"+match[2]);
        var replaced=input.replace(/a+/g,function(value){return "["+value.length+"]";});
        print("regexp",matches.join("|"),replaced,/^aaB/i.test(input));
    """,
    "runtime/typed_arrays.js": r"""
        var buffer=new ArrayBuffer(32),view=new DataView(buffer),bytes=new Uint8Array(buffer),words=new Int32Array(buffer);
        for(var i=0;i<bytes.length;i++)bytes[i]=(i*17+3)&255;
        view.setInt32(4,-12345678,true);view.setUint16(12,65530,false);words[5]=0x12345678;
        var checksum=0;for(var i=0;i<bytes.length;i++)checksum=(checksum*33+bytes[i])|0;
        print("typed",view.getInt32(4,true),view.getUint16(12,false),words[5],checksum);
    """,
    "runtime/json.js": r"""
        var value={name:"mercury",values:[1,true,null,"x"],nested:{b:2,a:1}};
        var encoded=JSON.stringify(value),decoded=JSON.parse(encoded),revived=JSON.parse('{"x":2,"y":3}',function(key,value){return typeof value==="number"?value*4:value;});
        print("json",encoded,decoded.values.join("|"),decoded.nested.a+decoded.nested.b,revived.x+revived.y);
    """,
    "runtime/date_math.js": r"""
        var date=new Date(1609459200123), checksum=0;
        for(var i=1;i<=100;i++)checksum+=Math.floor(Math.sin(i)*1000)+Math.ceil(Math.cos(i)*1000)+Math.round(Math.log(i)*100);
        print("date-math",date.getTime(),date.getUTCFullYear(),date.getUTCMonth(),date.getUTCDate(),checksum,Math.max(3,9,-1),Math.min(3,9,-1));
    """,
    "runtime/bigint.js": r"""
        var a=12345678901234567890n,b=987654321n; var c=(a*b)+(a>>7n)-(b<<11n);
        var values=[1n,2n,3n,4n,5n],product=1n;for(var value of values)product*=value;
        print("bigint",String(c),String(product),a>b,String(BigInt("9007199254740993")+1n));
    """,
}


def generated_cases():
    result = {}
    for count in (16, 64, 256):
        functions = []
        calls = []
        for index in range(count):
            functions.append(
                f"function fn{index}(value) {{ return (value + {index}) ^ {index * 17}; }}"
            )
            calls.append(f"checksum = (checksum + fn{index}({index + 3})) | 0;")
        result[f"size/many_functions_{count}.js"] = (
            "\n".join(functions)
            + "\nvar checksum = 0;\n"
            + "\n".join(calls)
            + f'\nprint("many-functions-{count}", checksum);\n'
        )

    for count in (32, 256, 1024):
        entries = ",\n".join(f"p{index}: {index * 3 % 997}" for index in range(count))
        result[f"size/many_properties_{count}.js"] = f"""
            var object = {{
            {entries}
            }};
            var checksum = 0, keys = Object.keys(object);
            for (var i = 0; i < keys.length; i++) checksum = (checksum * 31 + object[keys[i]]) | 0;
            print("many-properties-{count}", keys.length, checksum, object.p{count - 1});
        """

    for count in (16, 128, 512):
        arms = "\n".join(f"case {index}: return {index * 13 % 1009};" for index in range(count))
        result[f"size/large_switch_{count}.js"] = f"""
            function choose(value) {{
              switch (value) {{
                {arms}
                default: return -1;
              }}
            }}
            var checksum = 0;
            for (var i = -1; i <= {count}; i++) checksum = (checksum * 33 + choose(i)) | 0;
            print("large-switch-{count}", checksum, choose({count // 2}), choose({count + 1}));
        """

    for count in (8, 32, 128):
        declarations = ["var value0 = seed;"]
        for index in range(1, count + 1):
            declarations.append(f"var value{index} = value{index - 1} + {index};")
        captured = " + ".join(f"value{index}" for index in range(0, count + 1, max(1, count // 8)))
        result[f"size/closure_capture_{count}.js"] = f"""
            function build(seed) {{
              {' '.join(declarations)}
              return function (step) {{ value0 += step; return {captured}; }};
            }}
            var first = build(3), second = build(7);
            print("closure-capture-{count}", first(1), first(2), second(4));
        """

    for count in (64, 512, 2048):
        statements = []
        for index in range(count):
            statements.append(
                f"value = (Math.imul(value ^ {index}, 33) + {index * 7 + 1}) | 0;"
            )
        result[f"size/straight_line_{count}.js"] = (
            "var value = 1;\n"
            + "\n".join(statements)
            + f'\nprint("straight-line-{count}", value);\n'
        )
    return result


def normalized(source):
    return HEADER + dedent(source).strip() + "\n"


def generate(check):
    cases = dict(CASES)
    cases.update(generated_cases())
    expected = {ROOT / name: normalized(source) for name, source in cases.items()}

    if check:
        failures = []
        actual_files = set(ROOT.rglob("*.js")) if ROOT.exists() else set()
        for path, contents in expected.items():
            if not path.exists() or path.read_text() != contents:
                failures.append(str(path.relative_to(ROOT)))
        for path in actual_files - set(expected):
            failures.append(str(path.relative_to(ROOT)) + " (unexpected)")
        if failures:
            print("corpus is not up to date:\n" + "\n".join(sorted(failures)), file=sys.stderr)
            return 1
        print(f"corpus is current: {len(expected)} files")
        return 0

    ROOT.mkdir(parents=True, exist_ok=True)
    for old in ROOT.rglob("*.js"):
        old.unlink()
    for path, contents in sorted(expected.items()):
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(contents)
    print(f"generated {len(expected)} files in {ROOT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(generate("--check" in sys.argv[1:]))
