// Generated by tests/generate_corpus.py. Do not edit by hand.
function fib(n) {
  var a = 0, b = 1;
  for (var i = 0; i < n; i++) { var next = a + b; a = b; b = next; }
  return a;
}
var checksum = 0;
for (var i = 0; i <= 30; i++) checksum = (checksum + fib(i)) | 0;
print("fibonacci", fib(10), fib(20), fib(30), checksum);
