// Generated by tests/generate_corpus.py. Do not edit by hand.
function gcd(a, b) { while (b) { var next = a % b; a = b; b = next; } return a; }
var state = 0x12345678;
var checksum = 0;
for (var i = 1; i <= 2000; i++) {
  state = (Math.imul(state, 1664525) + 1013904223) | 0;
  checksum = (checksum + gcd((state >>> 0) % 100000 + 1, i * 37)) | 0;
}
print("gcd-lcg", state, checksum);
