// Generated by tests/generate_corpus.py. Do not edit by hand.
var values = [0, -0, 1, -1, 3.5, -7.25, 2147483647, -2147483648, Infinity, -Infinity, NaN];
var checksum = 0;
for (var i = 0; i < values.length; i++) {
  var value = values[i];
  checksum += (value | 0) ^ (value >>> 0);
}
print("numeric", checksum, 1 / values[1], Number.isNaN(values[10]), Math.imul(123456, 789));
