// Generated by tests/generate_corpus.py. Do not edit by hand.
function inspect(a,b){a=10;arguments[1]=20;return[a,b,arguments[0],arguments[1],arguments.length].join(":");}
function rest(first,...values){return first+":"+values.join(",")+":"+arguments.length;}
var arrow=()=>arguments.length;
print("arguments",inspect(1,2,3),rest(4,5,6,7),arrow());
