// Generated by tests/generate_corpus.py. Do not edit by hand.
var source=[1,,3], values=[0,...source,4,..."xy"], removed=values.splice(2,2,8,9,10);
values.unshift(-1); values.push(11); var mapped=values.map(function(v,i){return v===undefined?i:v*i;});
var checksum=0; for(var i=0;i<mapped.length;i++) checksum=(checksum+(mapped[i]||0))|0;
print("arrays",values.length,1 in source,removed.join("|"),values.join("|"),checksum);
