// Generated by tests/generate_corpus.py. Do not edit by hand.
async function calculate(value){var first=await Promise.resolve(value+1);try{await Promise.reject(3);}catch(error){first+=error;}return first*2;}
Promise.all([calculate(4),calculate(9)]).then(function(values){print("async",values.join(","));});
