// Generated by tests/generate_corpus.py. Do not edit by hand.
class Base { constructor(value){this.value=value;} get doubled(){return this.value*2;} method(step){return this.value+step;} static label(){return "base";} }
class Derived extends Base { constructor(value){super(value+1);} method(step){return super.method(step)*2;} set doubled(value){this.value=value/2;} static label(){return super.label()+"-derived";} }
var item=new Derived(10), first=item.method(3); item.doubled=50;
print("classes",first,item.value,Derived.label(),item instanceof Derived,item instanceof Base);
