// Generated by tests/generate_corpus.py. Do not edit by hand.
function counter(seed) {
  var value = seed;
  return { next: function(step){ value += step; return value; }, read: function(){ return value; } };
}
var counters = [];
for (let i = 0; i < 12; i++) counters.push(function(){ return i * i; });
var first = counter(10), second = counter(-3), checksum = 0;
for (var i = 0; i < counters.length; i++) checksum += counters[i]();
print("closures", first.next(2), first.next(5), second.next(7), first.read(), second.read(), checksum);
