// Generated by tests/generate_corpus.py. Do not edit by hand.
var object={valueOf:function(){return 7;},toString:function(){return "object";}};
var values=[null,undefined,false,true,0,-0,1,"", "12", object]; var checksum="";
for(var i=0;i<values.length;i++)checksum+=typeof values[i]+":"+Boolean(values[i])+"|";
print("coercions",+"12",object+3,String(object),null==undefined,null===undefined,0==false,checksum.length);
