// Generated by tests/generate_corpus.py. Do not edit by hand.
function collect(first=1,{x,y=3,...rest},[head,,...tail]){return [first,x,y,rest.z,head,tail.join(":"),arguments.length];}
var input={x:2,z:4}, array=[5,6,7,8]; var result=collect(undefined,input,array);
var a,b,remaining; [a,b,...remaining]=[9,10,11,12];
print("destructuring",result.join("|"),a,b,remaining.join(":"));
