// Generated by tests/generate_corpus.py. Do not edit by hand.
var log=[];
function work(value){try{log.push("try"+value);if(value%2)throw value;return value*2;}catch(error){log.push("catch"+error);return error+10;}finally{log.push("finally"+value);}}
var checksum=0; for(var i=0;i<6;i++)checksum+=work(i);
try{try{throw "inner";}finally{log.push("inner-finally");}}catch(error){log.push(error);}
print("exceptions",checksum,log.join(","));
