// Generated by tests/generate_corpus.py. Do not edit by hand.
function* sequence(limit){try{for(var i=0;i<limit;i++)yield i*i;}finally{yield "closed";}}
var iterator=sequence(5), output=[]; output.push(iterator.next().value); output.push(iterator.next().value); output.push(iterator.return(9).value); output.push(iterator.next().value); output.push(iterator.next().done);
function* delegated(){yield 1;yield* [2,3];return 4;} var second=delegated(), checksum=[]; var step; while(!(step=second.next()).done)checksum.push(step.value); checksum.push(step.value);
print("generators",output.join("|"),checksum.join("|"));
