// Generated by tests/generate_corpus.py. Do not edit by hand.
var closed=0;
var iterable={}; iterable[Symbol.iterator]=function(){var i=0;return{next:function(){return i<8?{value:i++,done:false}:{done:true};},return:function(){closed++;return{done:true};}};};
var checksum=0; for(var value of iterable){if(value===5)break;checksum=checksum*10+value;}
var spread=[...iterable];
print("iterators",checksum,closed,spread.join(","));
