// Generated by tests/generate_corpus.py. Do not edit by hand.
var events = [], key = "dynamic", symbol = Symbol("s");
var source = {a:1, get b(){events.push("get-b");return 2;}}; source[symbol] = 3;
var parent = {inherited:4};
var object = {__proto__:parent, before:0, ...source, [key]:5, method(x){return this.inherited+x;}, get value(){return this._v||6;}, set value(v){events.push("set");this._v=v;}};
object.value=7;
var descriptor=Object.getOwnPropertyDescriptor(object,"value");
print("objects",object.a,object.b,object[symbol],object.dynamic,object.method(8),object.value,descriptor.enumerable,parent.isPrototypeOf(object),events.join(","));
