// Generated by tests/generate_corpus.py. Do not edit by hand.
function Base(value){this.value=value;} Base.prototype.read=function(){return this.value;};
function Child(value){Base.call(this,value*2);} Child.prototype=Object.create(Base.prototype); Child.prototype.constructor=Child;
Child.prototype.bump=function(){this.value++;return this.value;};
var child=new Child(9);
print("prototypes",child.read(),child.bump(),child instanceof Child,child instanceof Base,Object.getPrototypeOf(child)===Child.prototype);
