// Generated by tests/generate_corpus.py. Do not edit by hand.
var log=[],target={value:2};
var proxy=new Proxy(target,{get:function(object,key,receiver){log.push("g"+String(key));return Reflect.get(object,key,receiver);},set:function(object,key,value,receiver){log.push("s"+String(key));return Reflect.set(object,key,value,receiver);},ownKeys:function(object){log.push("keys");return Reflect.ownKeys(object);}});
proxy.value+=5;proxy.extra=9;var keys=Object.keys(proxy);
print("proxy",proxy.value,proxy.extra,keys.join(","),log.join("|"));
