// Generated by tests/generate_corpus.py. Do not edit by hand.
var output=[];
for(let i=0;i<5;i++){let square=i*i;output.push(function(){return i+":"+square;});}
function outer(value){var shared=value;function left(){return ++shared;}function right(){shared*=2;return shared;}return[left,right];}
var pair=outer(3);
print("scoping",output.map(function(fn){return fn();}).join(","),pair[0](),pair[1](),pair[0]());
