// Generated by tests/generate_corpus.py. Do not edit by hand.
var first=Symbol("x"), second=Symbol.for("shared"), object={}; object[first]=3; object[second]=4; object.visible=5;
var symbols=Object.getOwnPropertySymbols(object), checksum=0; for(var i=0;i<symbols.length;i++)checksum+=object[symbols[i]];
print("symbols",symbols.length,checksum,Symbol.keyFor(second),String(first),Reflect.ownKeys(object).length);
