// Generated by tests/generate_corpus.py. Do not edit by hand.
function Node(left, right, value) { this.left = left; this.right = right; this.value = value; }
function build(depth, value) {
  if (depth === 0) return new Node(null, null, value);
  return new Node(build(depth - 1, value * 2 - 1), build(depth - 1, value * 2), value);
}
function check(node) { return node.left === null ? node.value : node.value + check(node.left) - check(node.right); }
var checksum = 0;
for (var i = 0; i < 20; i++) checksum += check(build(8, i + 1));
print("binary-trees", checksum, check(build(10, 1)));
