// Generated by tests/generate_corpus.py. Do not edit by hand.
var size = 120;
var graph = new Array(size);
for (var i = 0; i < size; i++) graph[i] = [(i * 7 + 3) % size, (i * 11 + 5) % size, (i + 1) % size];
var distance = new Int32Array(size);
for (var i = 0; i < size; i++) distance[i] = -1;
var queue = [0]; distance[0] = 0;
for (var head = 0; head < queue.length; head++) {
  var node = queue[head];
  for (var edge = 0; edge < graph[node].length; edge++) {
    var next = graph[node][edge];
    if (distance[next] === -1) { distance[next] = distance[node] + 1; queue.push(next); }
  }
}
var checksum = 0;
for (var i = 0; i < size; i++) checksum = (checksum * 31 + distance[i]) | 0;
print("graph", queue.length, checksum);
