// Generated by tests/generate_corpus.py. Do not edit by hand.
var checksum = 0, width = 80, height = 60;
for (var py = 0; py < height; py++) for (var px = 0; px < width; px++) {
  var x0 = px / width * 3.5 - 2.5, y0 = py / height * 2 - 1;
  var x = 0, y = 0, iteration = 0;
  while (x * x + y * y <= 4 && iteration < 50) {
    var nextX = x * x - y * y + x0;
    y = 2 * x * y + y0; x = nextX; iteration++;
  }
  checksum = (checksum + Math.imul(iteration, px + py + 1)) | 0;
}
print("mandelbrot", checksum);
