// Generated by tests/generate_corpus.py. Do not edit by hand.
function matrix(size, seed) {
  var result = new Array(size);
  for (var row = 0; row < size; row++) {
    result[row] = new Array(size);
    for (var column = 0; column < size; column++) result[row][column] = (row * 17 + column * 13 + seed) % 19;
  }
  return result;
}
function multiply(left, right) {
  var size = left.length, output = matrix(size, 0);
  for (var row = 0; row < size; row++) for (var column = 0; column < size; column++) {
    var value = 0;
    for (var index = 0; index < size; index++) value += left[row][index] * right[index][column];
    output[row][column] = value;
  }
  return output;
}
var output = multiply(matrix(18, 3), matrix(18, 7));
var checksum = 0;
for (var i = 0; i < output.length; i++) checksum += output[i][i] + output[i][17 - i];
print("matrix", checksum, output[3][7]);
