// Generated by tests/generate_corpus.py. Do not edit by hand.
var bodies = [
  {x:0,y:0,z:0,vx:0,vy:0,vz:0,m:1},
  {x:1,y:0,z:0,vx:0,vy:0.8,vz:0,m:0.001},
  {x:-1.5,y:0.2,z:0,vx:-0.1,vy:-0.6,vz:0,m:0.0007},
  {x:0.3,y:2,z:0.1,vx:-0.5,vy:0.1,vz:0,m:0.0002}
];
function advance(dt) {
  for (var i = 0; i < bodies.length; i++) for (var j = i + 1; j < bodies.length; j++) {
    var a = bodies[i], b = bodies[j], dx = a.x-b.x, dy=a.y-b.y, dz=a.z-b.z;
    var distance = Math.sqrt(dx*dx+dy*dy+dz*dz), scale = dt/(distance*distance*distance);
    a.vx -= dx*b.m*scale; a.vy -= dy*b.m*scale; a.vz -= dz*b.m*scale;
    b.vx += dx*a.m*scale; b.vy += dy*a.m*scale; b.vz += dz*a.m*scale;
  }
  for (var i = 0; i < bodies.length; i++) { var b=bodies[i]; b.x+=dt*b.vx; b.y+=dt*b.vy; b.z+=dt*b.vz; }
}
function energy() {
  var result=0;
  for(var i=0;i<bodies.length;i++){var a=bodies[i];result+=a.m*(a.vx*a.vx+a.vy*a.vy+a.vz*a.vz)/2;for(var j=i+1;j<bodies.length;j++){var b=bodies[j],dx=a.x-b.x,dy=a.y-b.y,dz=a.z-b.z;result-=a.m*b.m/Math.sqrt(dx*dx+dy*dy+dz*dz);}}
  return result;
}
for(var i=0;i<2000;i++) advance(0.001);
print("nbody", energy().toFixed(12), bodies[1].x.toFixed(9));
