// Generated by tests/generate_corpus.py. Do not edit by hand.
function countPrimes(limit) {
  var composite = new Uint8Array(limit + 1);
  var count = 0, checksum = 0;
  for (var value = 2; value <= limit; value++) {
    if (!composite[value]) {
      count++; checksum = (checksum + value) | 0;
      if (value * value <= limit) {
        for (var multiple = value * value; multiple <= limit; multiple += value) composite[multiple] = 1;
      }
    }
  }
  return [count, checksum];
}
var result = countPrimes(10000);
print("sieve", result[0], result[1]);
