// Generated by tests/generate_corpus.py. Do not edit by hand.
function randomValues(length) {
  var state = 1, values = [];
  for (var i = 0; i < length; i++) { state = (Math.imul(state, 1103515245) + 12345) | 0; values.push(state); }
  return values;
}
function quicksort(values, left, right) {
  if (left >= right) return;
  var pivot = values[(left + right) >> 1], i = left, j = right;
  while (i <= j) {
    while (values[i] < pivot) i++;
    while (values[j] > pivot) j--;
    if (i <= j) { var value = values[i]; values[i++] = values[j]; values[j--] = value; }
  }
  if (left < j) quicksort(values, left, j);
  if (i < right) quicksort(values, i, right);
}
var values = randomValues(1000);
quicksort(values, 0, values.length - 1);
var checksum = 0;
for (var i = 0; i < values.length; i += 17) checksum = (checksum + values[i]) | 0;
print("sorting", values[0], values[values.length - 1], checksum);
