// Generated by tests/generate_corpus.py. Do not edit by hand.
function A(i, j) { var ij = i + j; return 1 / ((ij * (ij + 1) / 2) + i + 1); }
function multiplyAv(input, output) {
  for (var i = 0; i < input.length; i++) { var sum = 0; for (var j = 0; j < input.length; j++) sum += A(i, j) * input[j]; output[i] = sum; }
}
function multiplyAtv(input, output) {
  for (var i = 0; i < input.length; i++) { var sum = 0; for (var j = 0; j < input.length; j++) sum += A(j, i) * input[j]; output[i] = sum; }
}
var n = 70, u = new Float64Array(n), v = new Float64Array(n), temp = new Float64Array(n);
for (var i = 0; i < n; i++) u[i] = 1;
for (var iteration = 0; iteration < 8; iteration++) { multiplyAv(u, temp); multiplyAtv(temp, v); multiplyAv(v, temp); multiplyAtv(temp, u); }
var vbv = 0, vv = 0;
for (var i = 0; i < n; i++) { vbv += u[i] * v[i]; vv += v[i] * v[i]; }
print("spectral-norm", Math.sqrt(vbv / vv).toFixed(9));
