// Generated by tests/generate_corpus.py. Do not edit by hand.
var map = new Map(), set = new Set();
for (var i = 0; i < 200; i++) { var key = "k" + (i % 73); map.set(key, (map.get(key) || 0) + i); set.add(i % 41); }
var checksum = 0;
map.forEach(function (value, key) { checksum = (checksum + value * key.length) | 0; });
var iterated = 0;
for (var value of set) iterated = (iterated * 33 + value) | 0;
print("maps-sets", map.size, set.size, checksum, iterated, map.has("k17"));
