// Generated by tests/generate_corpus.py. Do not edit by hand.
var weakMap = new WeakMap(), weakSet = new WeakSet(), objects = [];
for (var i = 0; i < 50; i++) { var object = {index:i}; objects.push(object); weakMap.set(object, i*i); if (i%2===0) weakSet.add(object); }
var checksum = 0, membership = 0;
for (var i = 0; i < objects.length; i++) { checksum += weakMap.get(objects[i]); membership += weakSet.has(objects[i]) ? 1 : 0; }
print("weak-collections", checksum, membership);
